---
version: 1.0.0

client:
  organization: org1
  logging:
    level: debug
  cryptoconfig:
    path: /nfsvolume/crypto-config
  credentialStore:
    path: /tmp/state-store
  cryptoStore:
    path: /tmp/msp
  tlsCerts:
    client:
      key:
        path: /nfsvolume/crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/tls/client.key
      cert:
        path: /nfsvolume/crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/tls/client.crt

channels:
  _default:
    peers:
      peer0.org1.example.com:
      peer1.org1.example.com:

organizations:
  org1:
    mspid: Org1MSP
    cryptoPath: peerOrganizations/org1.example.com/users/{username}@org1.example.com/msp
    peers:
      - peer0.org1.example.com
      - peer1.org1.example.com
  org2:
    mspid: Org2MSP
    cryptoPath:  peerOrganizations/org2.example.com/users/{username}@org2.example.com/msp
    peers:
      - peer0.org2.example.com
      - peer1.org2.example.com
  ordererorg:
    mspID: OrdererMSP
    cryptoPath: ordererOrganizations/example.com/users/{username}@example.com/msp

orderers:
  orderer.example.com:
    url: orderer.example.com:7050
    grpcOptions:
      ssl-target-name-override: orderer.example.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
    tlsCACerts:
      path: /nfsvolume/crypto-config/ordererOrganizations/example.com/tlsca/tlsca.example.com-cert.pem

peers:
  peer0.org1.example.com:
    url: peer0.org1.example.com:7051
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
    tlsCACerts:
      path: /nfsvolume/crypto-config/peerOrganizations/org1.example.com/tlsca/tlsca.org1.example.com-cert.pem

  peer1.org1.example.com:
    url: peer1.org1.example.com:7151
    grpcOptions:
      ssl-target-name-override: peer1.org1.example.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
    tlsCACerts:
      path: /nfsvolume/crypto-config/peerOrganizations/org1.example.com/tlsca/tlsca.org1.example.com-cert.pem

  peer0.org2.example.com:
    url: peer0.org2.example.com:8051
    grpcOptions:
      ssl-target-name-override: peer0.org2.example.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
    tlsCACerts:
      path: /nfsvolume/crypto-config/peerOrganizations/org2.example.com/tlsca/tlsca.org2.example.com-cert.pem

  peer1.org2.example.com:
    url: peer1.org2.example.com:10051
    grpcOptions:
      ssl-target-name-override: peer0.org2.example.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
    tlsCACerts:
      path: /nfsvolume/crypto-config/peerOrganizations/org2.example.com/tlsca/tlsca.org2.example.com-cert.pem

entityMatchers:
  peer:
    - pattern: peer0.org1.example.com
      urlSubstitutionExp: 192.168.51.10:7051
      sslTargetOverrideUrlSubstitutionExp: peer0.org1.example.com
      mappedHost: peer1.org1.example.com
    - pattern: peer1.org1.example.com
      urlSubstitutionExp: 192.168.51.10:8051
      sslTargetOverrideUrlSubstitutionExp: peer1.org1.example.com
      mappedHost: peer0.org2.example.com
    - pattern: peer0.org2.example.com
      urlSubstitutionExp: 192.168.51.10:9051
      sslTargetOverrideUrlSubstitutionExp: peer0.org2.example.com
      mappedHost: peer1.org2.example.com
    - pattern: peer1.org2.example.com
      urlSubstitutionExp: 192.168.51.10:10051
      sslTargetOverrideUrlSubstitutionExp: peer1.org2.example.com
      mappedHost: peer0.org1.example.com
  orderer:
    - pattern: orderer.example.com
      urlSubstitutionExp: 192.168.51.10:7050
      sslTargetOverrideUrlSubstitutionExp: orderer.example.com
      mappedHost: orderer.example.com
